
const BIBLIOGRAPHIC = 'BIBLIOGRAPHIC';
const HOLDINGS = 'HOLDINGS';
const AUTHORITY = 'AUTHORITY';
const COMMUNITY = 'COMMUNITY';
const CLASSIFICATION = 'CLASSIFICATION';
const UNKNOWN = 'UNKNOWN';

const MARC_RECORD_FORMATS = {
  BIBLIOGRAPHIC,
  HOLDINGS,
  AUTHORITY,
  COMMUNITY,
  CLASSIFICATION,
  UNKNOWN,
};

module.exports = {
  MARC_RECORD_FORMATS,
}